/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedSaRouteImport } from './routes/_authenticated/sa'
import { Route as AuthenticatedSaHistoryRouteImport } from './routes/_authenticated/sa-history'
import { Route as AuthenticatedSaListRouteImport } from './routes/_authenticated/sa-list'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaRoute = AuthenticatedSaRouteImport.update({
  id: '/sa',
  path: '/sa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaHistoryRoute = AuthenticatedSaHistoryRouteImport.update({
  id: '/sa-history',
  path: '/sa-history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaListRoute = AuthenticatedSaListRouteImport.update({
  id: '/sa-list',
  path: '/sa-list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/hr': typeof AuthenticatedHrRoute
  '/sa': typeof AuthenticatedSaRoute
  '/sa-history': typeof AuthenticatedSaHistoryRoute
  '/sa-list': typeof AuthenticatedSaListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/hr': typeof AuthenticatedHrRoute
  '/sa': typeof AuthenticatedSaRoute
  '/sa-history': typeof AuthenticatedSaHistoryRoute
  '/sa-list': typeof AuthenticatedSaListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/sa': typeof AuthenticatedSaRoute
  '/_authenticated/sa-history': typeof AuthenticatedSaHistoryRoute
  '/_authenticated/sa-list': typeof AuthenticatedSaListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/approvals'
    | '/hr'
    | '/sa'
    | '/sa-history'
    | '/sa-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/approvals'
    | '/hr'
    | '/sa'
    | '/sa-history'
    | '/sa-list'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/reset-password'
    | '/_authenticated/approvals'
    | '/_authenticated/hr'
    | '/_authenticated/sa'
    | '/_authenticated/sa-history'
    | '/_authenticated/sa-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa': {
      id: '/_authenticated/sa'
      path: '/sa'
      fullPath: '/sa'
      preLoaderRoute: typeof AuthenticatedSaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa-history': {
      id: '/_authenticated/sa-history'
      path: '/sa-history'
      fullPath: '/sa-history'
      preLoaderRoute: typeof AuthenticatedSaHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sa-list': {
      id: '/_authenticated/sa-list'
      path: '/sa-list'
      fullPath: '/sa-list'
      preLoaderRoute: typeof AuthenticatedSaListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedSaRoute: typeof AuthenticatedSaRoute
  AuthenticatedSaHistoryRoute: typeof AuthenticatedSaHistoryRoute
  AuthenticatedSaListRoute: typeof AuthenticatedSaListRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedSaRoute: AuthenticatedSaRoute,
  AuthenticatedSaHistoryRoute: AuthenticatedSaHistoryRoute,
  AuthenticatedSaListRoute: AuthenticatedSaListRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
